// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK8Txa4RmlI4sIimGI6wil8j_ctcUhkkk',
    appId: '1:19802712993:web:6a1b0d08fbe0b785b7b9e0',
    messagingSenderId: '19802712993',
    projectId: 'njangi-pay',
    authDomain: 'njangi-pay.firebaseapp.com',
    storageBucket: 'njangi-pay.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw84EcygY_KeyBeA2y2bP9_OBP0huztio',
    appId: '1:19802712993:android:695be487aea58dcdb7b9e0',
    messagingSenderId: '19802712993',
    projectId: 'njangi-pay',
    storageBucket: 'njangi-pay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkwoS7cQpYgTf-G_nXyyYhRPvkv5HyMgM',
    appId: '1:19802712993:ios:778c808ccc5d1d22b7b9e0',
    messagingSenderId: '19802712993',
    projectId: 'njangi-pay',
    storageBucket: 'njangi-pay.firebasestorage.app',
    iosClientId: '19802712993-l6bh81qahq5ocgiub21nubb6bis39ogg.apps.googleusercontent.com',
    iosBundleId: 'com.example.njangiPay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkwoS7cQpYgTf-G_nXyyYhRPvkv5HyMgM',
    appId: '1:19802712993:ios:778c808ccc5d1d22b7b9e0',
    messagingSenderId: '19802712993',
    projectId: 'njangi-pay',
    storageBucket: 'njangi-pay.firebasestorage.app',
    iosClientId: '19802712993-l6bh81qahq5ocgiub21nubb6bis39ogg.apps.googleusercontent.com',
    iosBundleId: 'com.example.njangiPay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK8Txa4RmlI4sIimGI6wil8j_ctcUhkkk',
    appId: '1:19802712993:web:2876601667ee192db7b9e0',
    messagingSenderId: '19802712993',
    projectId: 'njangi-pay',
    authDomain: 'njangi-pay.firebaseapp.com',
    storageBucket: 'njangi-pay.firebasestorage.app',
  );
}
